stages:
    - build
    - codeStyle
    - integrationTest
    - deploy

building:
    stage: build
    tags:
        - navi
    script:
        - cd src/cat
        - make s21_cat
        - cd ../grep
        - make s21_grep
    artifacts:
        paths:
            - src/cat/s21_cat
            - src/grep/s21_grep
        expire_in: 30 days
    after_script:
        - ./telegram.sh

codeStyle:
    stage: codeStyle
    tags:
        - navi
    script:
        - cd src
        - ./qwest.sh
    after_script:
        - echo "$CI_JOB_STATUS"
        - ./telegram.sh

integrationTest:
    stage: integrationTest
    tags:
        - navi
    when: on_success
    script:
        - cd src/cat
        - bash ./test_cat.sh
        - cd ../grep
        - bash ./test_grep.sh
    after_script:
        - ./telegram.sh

deploy:
    stage: deploy
    tags:
        - navi
    script:
        - ./deploy.sh
    after_script:
        - ./telegram.sh
    when: manual
